CREATE TABLE IF NOT EXISTS migrations_run (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) UNIQUE NOT NULL,
  run_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  is_admin BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT IGNORE INTO users (email, password_hash, name, is_admin)
VALUES ('admin@example.com', '$2b$12$.HEQahTxSFIy/dvG9Hyqs./4Lj48XKKnjUVQG0bCnFgqy18aAN8iu', 'Admin', TRUE);
-- password: admin123
